name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set Docker tag
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} .
          docker tag ${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} ${{ secrets.IMAGE_NAME }}:latest
      - name: Push Docker images
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          docker push ${{ secrets.IMAGE_NAME }}:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker images for DockerHub
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/checky-backend:${{ env.SHORT_SHA }}
          docker tag ${{ secrets.IMAGE_NAME }}:latest docker.io/${{ secrets.DOCKERHUB_USERNAME }}/checky-backend:latest
      - name: Push Docker images (DockerHub)
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/checky-backend:${{ env.SHORT_SHA }}
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/checky-backend:latest
